[tool.poetry]
name = "Echo"
version = "2.0.1"
description = ""
authors = ["Eclipse Darkpaw <random-college-bi.tumblr.com>"]

[tool.poetry.dependencies]
python = "^3.10"
discord = "^1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
