[tool.poetry]
name = "echo"
version = "1.1.2"
description = ""
authors = ["Eclipse Darkpaw <random-college-bi.tumblr.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"
flask = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
